### ISSUE TITLE
Mixin error

### ISSUE THREAD

**Issue by Sunconure11** [Xires87/Haemorrhage#1]
https://pastebin.com/px6axP1H

@Xires87

**Comment by Xires87** [comment]
It's compatibility issue. I will fix it in next update.

By the time, please, try using older version of Haemorrhage (1.0.3). It should work.
The newest version of Haemorrhage doesn't affect gameplay, so you won't lose anything.

**Comment by Xires87** [comment]
Fixed in x.0.5 versions
